baseURL = 'https://train.sh/'
languageCode = 'en-us'
title = 'Welcome to train.sh'
theme = 'PaperMod'
hasCJKLanguage = true
enableEmoji = true

# Build settings
buildFuture = true
buildDrafts = false
timeZone = 'Asia/Shanghai'

# Basic configuration
[pagination]
  pagerSize = 10

[params]
  description = "This blog covers artificial intelligence, productivity, and personal insights."
  author = "Binbin Shen"
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  ShowPostNavLinks = true
  mermaid = true
  hasCJKLanguage = true
  ReadingTimeCharPerMin = 300
  disableSpecial1stPost = true

[params.homeInfoParams]
  Title = "👋 Welcome"
  Content = """
  A personal space where I document my learning journey in artificial intelligence, share productivity experiments, and record thoughts on technology and life. Nothing groundbreaking here, just notes and reflections from someone trying to understand the world a bit better each day.
  <br/>
  <br/>
  If you'd like to get in touch, you can reach me at binbin@train.sh
  """

# Menu configuration
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3

[taxonomies]
  tag = "tags"

# Syntax highlighting
[markup]
  [markup.highlight]
    style = 'monokai'

  [markup.goldmark.renderer]
    unsafe = true  # Allow HTML

  [markup.goldmark.extensions]
    typographer = false
    linkify = true
    strikethrough = true
    table = true
    taskList = true
  [markup.goldmark.parser]
    attribute = true
